### ISSUE TITLE
Diagrama Base de Datos

### ISSUE THREAD

**Issue by sebastianjorc** [sebastianjorc/Plataforma-Cl-nica-Odontologica#1]
Debe contener los datos de cada tipo de usuario, datos financieros y tecnicos (dentales).
No necesita ser definitivo, ya qué se pretende partir de éste para analizar los pro-contras, y generar una discusión al respecto.

**Comment by sebastianjorc** [comment]
A modo de comentario/recomendación. Creo que podrían crearse las siguientes tablas:
01. Usuarios: Para todo aquel que utilice la plataforma, con ID y Pass para acceder.
02. Alumnos: Servirá para listar cada uno los usuarios pertenecientes a esta categoría, y facilitar su manejo
03. Pacientes: Servirá para listar cada uno los usuarios pertenecientes a esta categoría, y facilitar su manejo
04. Calendarización: Aquí agendar todas las horas (Alumno-Paciente), con sus fechas respectivas y otros.
05. Diagnosticos: Listar diagnósticos por Paciente y Alumno.
06. Servicios: Lista de servicios que dará la clinica.
07. Insumos: Lista de insumos, que ayudará a llevar la contabilidad de gastos.
08. Finanzas: Datos de ingresos, egresos, fondo general, etc.
09. Secretarias : (SSI hay más de una) Lo mismo que el 02 y 03
10. Tesorera : Lo mismo que el 09.

**Comment by ayutia** [comment]
Me adjudicare esta issue, y en lo posible vere el tema del servidor que lo más probable que lo aloje en mi computador y lo puedo dejar prendido.

**Comment by sebastianjorc** [comment]
![databasemodel](https://cloud.githubusercontent.com/assets/11509689/24729999/610ef6be-1a37-11e7-95df-b19858e3a0cd.png)
Realicé un esquema básico de la base de datos en UML (tuve problemas con el modelador de la base de datos y no lo guardaba), favor revisar y comentarla, para ir remodelandola, y quién quiera acabar los detalles pueda tomar esa idea.

PD: Insumo y Finanza quedan libre porque a mi considerar no pertenecen particularmente a ningún usuario, sino a la plataforma en sí.
