### ISSUE TITLE
UML Casos de Uso Practicante

### ISSUE THREAD

**Issue by sebastianjorc** [sebastianjorc/Plataforma-Cl-nica-Odontologica#4]
Debe contener los tipos datos y funciones que manejará y llevará a cabo este tipo de usuario.

No necesita ser definitivo, ya qué se pretende partir de éste para analizar los pro-contras, y generar una discusión al respecto.

**Comment by NortonDanteI** [comment]
¿Que es esto?, no es la plataforma del médico?

**Comment by sebastianjorc** [comment]
En cierta forma sí. Es a lo que tendrá acceso el médico (El proyecto se hace en relación a la clínica dental de la U, y los que atenderán serán los alumnos en práctica, al menos a mi entender.)

**Comment by NortonDanteI** [comment]
😨

**Comment by sebastianjorc** [comment]
@NortonDanteI  ![bitmoji](https://render.bitstrips.com/v2/cpanel/10136823-220154472_12-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by NortonDanteI** [comment]
PIDO

**Comment by NortonDanteI** [comment]
terminado
