### ISSUE TITLE
UML Casos de Uso Administrador

### ISSUE THREAD

**Issue by sebastianjorc** [sebastianjorc/Plataforma-Cl-nica-Odontologica#5]
Debe contener los tipos datos y funciones que manejará y llevará a cabo este tipo de usuario.

No necesita ser definitivo, ya qué se pretende partir de éste para analizar los pro-contras, y generar una discusión al respecto.

**Comment by sebastianjorc** [comment]
Tengo la duda de si juntar el tipo de usuario Administrador con Tesorero
La labor del Administrador debería ser solo el poder eliminas y agregar usuarios.
Y la labor del tesorero es todo lo relacionado a finanzas, Gastos, costos e ingresos.

**Comment by NortonDanteI** [comment]
Yo creo que el administrador debe poder ver el inventario médico ej: agujas, camillas, mascarillas,etc. Y de ir actualizando el recurso humano de la clínica. ejemplo si tengo al doctor A ponerle para que el administrador pueda agregar a su lista de profesionales al doctor A con sus datos y la especialidad que maneja para que asi la clinica pueda saber que areas de odontologia tiene cubiertas. y la disponibilidad, ejemplo si un doctor de X especialidad esta de viaje por ejemplo o enfermo, en resumidas cuentas No disponible. El administrador debe tener acceso a la plataforma para que ese servicio no pueda estar activo. Porque seria raro que en plataforma te mostrara que ese medico esta atendiendo y haciendo un servicio siendo que no se puede generar.
