### ISSUE TITLE
UML Casos de uso Tesorero

### ISSUE THREAD

**Issue by sebastianjorc** [sebastianjorc/Plataforma-Cl-nica-Odontologica#6]
Debe contener los tipos datos y funciones que manejará y llevará a cabo este tipo de usuario.

No necesita ser definitivo, ya qué se pretende partir de éste para analizar los pro-contras, y generar una discusión al respecto.

**Comment by sebastianjorc** [comment]
Tengo la duda de si juntar el tipo de usuario Administrador con Tesorero
La labor del Administrador debería ser solo el poder eliminas y agregar usuarios.
Y la labor del tesorero es todo lo relacionado a finanzas, Gastos, costos e ingresos.

**Comment by NortonDanteI** [comment]
Joshua tengo entendido que la secretaria es la encargada de: 1- ver disponibilidad el médico, 2 - reservar horas en el calendario con el nombre del paciente, 3- generar las boletas de honorarios, 4- Recibir el dinero. Por lo que el Tesorero es inexistente.

**Comment by NortonDanteI** [comment]
Separados esta bien. Puede ser: 1- Ver total ingresos diarios. 2- recuento semanal, 3- recuento por años onda como un historial. 4- Ver gastos generados por la clínica divididos en *personal, *gastos comunes en inventario, *en Nueva implementación médica, * en gastos estructurales si se genero alguno. PD: En el caso de ingresos diarios saber por parte de que médico se genero ese ingreso por ejemplo si el médico A ha atentido a 15 pacientes con una recaudacion X que el tesorero sepa que esa recaudacion X fue producida de esa fuente, y lo mismo para los otros médicos.

**Comment by NortonDanteI** [comment]
Yo hago esta issue O la vas a hacer tu?

**Comment by sebastianjorc** [comment]
@NortonDanteI Tómala tu, yo ya te la asigné
